### ISSUE TITLE
How do I clear the recorded lines?

### ISSUE THREAD

**Issue by Sur1ngware** [aaronhowser1/Ariadnes-Thread#4]
Hello, I like your mod very much, but now there is a problem: I don't know how to clear the lines that were once recorded, their number is too much and it kind of obstructs my view.

**Comment by aaronhowser1** [comment]
Sneak right-click the item while it's not recording. The tooltip should say this, I think

**Comment by Sur1ngware** [comment]
> Sneak right-click the item while it's not recording. The tooltip should say this, I think

I didn't notice this, thank you very much!
